### ISSUE TITLE
User can play the game

### ISSUE THREAD

**Issue by LukeYasu** [LukeYasu/pokemon-wordle#1]
## 📐 Functionality

User will be able to play a game and guess the pokemon where their attributes(type, height, weight, generation, evolution stage) will turn green to indicate that they match the mystery pokemon. If the attributes do not match, they will turn red to indicate that they do not match. If the mystery pokemon attribute is greater than the attribute of the guessed pokemon, there will be an up arrow indicating that the attribute for the correct mystery pokemon is greater than the attribute of the guessed pokemon. This does not include the types attribute. When they guess correctly, they will be shown a sprite of the guessed mystery pokemon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-10-01 at 10 29 03 AM](https://github.com/user-attachments/assets/b521b921-5109-4c8e-ad12-196989ad19a4)
![Screenshot 2024-10-01 at 10 29 48 AM](https://github.com/user-attachments/assets/48c6fe5d-7353-4195-8356-3a0a79bc288e)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a header element in HTML with the proper images/design and logo inside the container element
- [x] Underneath the buttons create a `required` text input with an enter button that submits the text input to a `form`
- [x] Create the headers for all the names of the attributes 
- [x] Underneath the attribute headers create a scrollbox for where all of the pokemon attributes will be seen
- [x] add additional images and styling at the bottom to complete the pokedex look
- [x] create a mock guess entry that has the pokemon name, 1 of 2 types correct, one correct attribute, one less than attribute, and one greater than attribute
- [ ] Adjust the CSS to be responsive and fit mobile and desktop views
- [ ] use the pokeapi to fetch attribute data from a pokemon of your choice and put those attributes into an object called `mysteryPokemon` (random pokemon as the mystery pokemon will come later)
- [ ] use the pokemon name from the form text input and fetch the data from pokeapi for each of the attributes(name, types, weight, height, generation, evo stage, sprites)
- [ ] after you fetch the data from pokeapi, put the attribute data into an array of objects called `pokemonGuesses`
- [ ] create an array of objects with image source links called guessBackground = [{green: 'src link'}, {red: 'src link'}, {redUp: 'src link'}, {redDown: 'src link'}]
- [ ] check to see if any of the attributes match the mysteryPokemon using conditionals
  - [ ] if the name attribute does not match the mystery pokemon, `pokemonBGColor` = 'red'
  - [ ] if type 1 does not match any of the types of the mystery pokemon, `type1BG` = red
  - [ ] if type 2 does not match any of the types of the mystery pokemon, `type2BG` = red
  - [ ] if weight equal mysteryPokemon weight, weightBG = 'green'
    - [ ] if weight is < mysteryPokemon weight, weighBG = 'redUp'
    - [ ] if weight is > mysteryPokemon weight, weighBG = 'redDown'
  - [ ] if height equal mysteryPokemon height, heightBG = `green`
    - [ ] if height is < mysteryPokemon height, heightBG = `redUp`
    - [ ] if height is > mysteryPokemon height, heightBG = `redDown`
  - [ ] if generation equal mysteryPokemon generation, genBG = `green`
    - [ ] if generation is < mysteryPokemon generation, genBG = `redUp`
    - [ ] if generation is > mysteryPokemon generation, genBG = `redDown`
  - [ ] if evoStage equal mysteryPokemon evoStage, evoStageBG = `green`
    - [ ] if evoStage is < mysteryPokemon evoStage, evoStageBG = `redUp`
    - [ ] if evoStage is > mysteryPokemon evoStage, evoStageBG = `redDown`
- [ ] Where the pokemon guesses should go and be displayed, create a div element with a game-container and row class
- [ ] inside that div, you will be creating a row with 6 columns using the renderGuess function
  - [ ] you will create a div element with the background-image guessBackground = the value of pokemonBGColor, and setting the attribute 'guess-box' class and setting the src attribute to the sprites attribute
  - [ ]create a div element with the background-image guessBackground = the value of type1BG and setting the attribute 'guess-box-top-half' class adding the text of the type inside of the div element
  - [ ]create a div element with the background-image guessBackground = the value of type2BG and setting the attribute 'guess-box-bot-half' class adding the text of the type inside of the div element
  - [ ]create a div element with the background-image guessBackground = the value of weighBG and setting the attribute 'guess-box' class adding the text of the type inside of the div element
  - [ ]create a div element with the background-image guessBackground = the value of heightBG and setting the attribute 'guess-box' class adding the text of the type inside of the div element
  - [ ]create a div element with the background-image guessBackground = the value of genBG and setting the attribute 'guess-box' class adding the text of the type inside of the div element
  - [ ]create a div element with the background-image guessBackground = the value of evoStageBG and setting the attribute 'guess-box' class adding the text of the type inside of the div element
  - [ ] append to the div class=row
