### ISSUE TITLE
Feature: User can view hints

### ISSUE THREAD

**Issue by LukeYasu** [LukeYasu/pokemon-wordle#3]
## 📐 Functionality

user can click on a button to see a collection of dropdown menus where each dropdown menu is a different hint. The first hint will be a blurry silhouette of the mystery pokemon, the second hint will be the first and last letter of their name, the third hint being a  blurry colored image and the fourth hint having every other letter in the mystery pokemon's name.

## 🖼️ Wireframes
![Screenshot 2024-10-07 at 10 56 49 AM](https://github.com/user-attachments/assets/da7d147b-93fb-452d-9450-f8ad9e90cd2a)
![Screenshot 2024-10-07 at 11 18 15 AM](https://github.com/user-attachments/assets/611c3bc0-c53c-4a43-a657-d50fd4727df1)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] create a button with the text 'hint' 
- [ ] add an event listener for the hint button that listens for when the hint button is clicked
- [ ] create the hint box that has a scrollbox with three dropdown menus and an x button at the top right
- [ ] add an event listener that listens for when the x button is pressed
- [ ] set the display to hidden until the hint button is clicked
- [ ] make sure that the hint box is responsive
- [ ] in the first dropdown menu, add the mystery pokemon sprite with the brightness at 0 and blur set to 3px
- [ ] in the second dropdown menu, add the second hint
  - [ ] create a variable called hint2Name
  - [ ] loop over the mystery pokemon name
    - [ ] if i = 0, append the letter to the hint2Name variable
    - [ ] if i = pokemon name length -1 then append the letter the hint2Name variable
    - [ ] else append `_` to the hint2Name variable
- [ ] for the third hint add the mystery pokemon sprite and add a blur effect
  - [ ] for the fourth hint for every other letter in the mystery pokemon's name ad it to a variable called hint4Name with `_` between each letter
