### ISSUE TITLE
Feature: User can autocomplete their text input

### ISSUE THREAD

**Issue by LukeYasu** [LukeYasu/pokemon-wordle#5]
## 📐 Functionality

when the user starts typing in a pokemon, the text input will pull up a dropdown menu of all the pokemon with it's sprite that match the text input. The user will be able to select the pokemon from the dropdown menu and it will autofill the pokemon that they selected. 

## 🖼️ Wireframes

![Screenshot 2024-10-08 at 12 21 30 PM](https://github.com/user-attachments/assets/4731435f-689a-472e-834e-13db13cbc1b6)

![Screenshot 2024-10-08 at 12 21 43 PM](https://github.com/user-attachments/assets/ab8449d1-0b70-41b6-93c4-6518fe62a3a6)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] fetch all of the pokemon names and it's sprite url and put them into a global variable as an array of objects
- [ ] add an event litener to the text input
  - [ ] for each keystroke check if the text input matches any of the pokemon names in the global variable within the length of the text input
  - [ ] if the text input is equal to the pokemon names first characters according to the text input length, add it to a dropdown select menu
  - [ ] for each pokemon in the dropdown also add the sprite image to go along with it
